[package]
name = "c3po-example"
version = "0.1.0"
authors = ["Jonathan Lemos <jonathanlemos@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
c3po = {path = ".."}