use super::super::cursor::cursor::Cursor;
use super::super::parse::parse::Parse;

/// The output type of `Parser::parse`.
pub struct ParserOutput<'a, TLexeme, TOutput> {
    beginning: Cursor<'a, TLexeme>,
    kind: String,
    parse: Parse<'a, TLexeme, TOutput>,
}

impl<'a, TLexeme, TOutput> ParserOutput<'a, TLexeme, TOutput> {
    /// Creates a new ParserOutput
    /// 
    /// # Arguments
    /// * `parse`     - A parse generated by a parsing function. See `Parser::func` for details.
    /// * `beginning` - A Cursor pointing to the first token of the parse.
    /// * `kind`      - What kind of value this parse has (on success).
    pub fn new<S: Into<String>>(parse: Parse<'a, TLexeme, TOutput>, beginning: Cursor<'a, TLexeme>, kind: S) -> Self {
        ParserOutput {
            beginning,
            kind: kind.into(),
            parse
        }
    }

    /// A Cursor pointing to the first token of the parse.
    pub fn beginning(&self) -> &Cursor<TLexeme> {
        &self.beginning
    }

    /// What kind of value this parse should have.
    pub fn kind(&self) -> &str {
        &self.kind
    }

    /// The parse itself.
    pub fn parse(&self) -> &Parse<TLexeme, TOutput> {
        &self.parse
    }
}